In [1]:
import numpy as np
from numpy.linalg import svd
import matplotlib.pyplot as plt
from matplotlib.pyplot import imshow

In [28]:
def plot_svd(A):
    n = len(A)
    U,S,V = svd(A)
    
    imgs = []
    for i in range(n):
        imgs.append(S[i]*np.outer(U[:,i],V[i]))
    print(np.round(imgs,2))   
     
        
    combined_imgs = []
    
    for i in range(n):
        img = sum(imgs[:i+1])
    combined_imgs.append(img)
        
    print("\nCombining all the above ones , we get our actual matrix A :")   
    print(combined_imgs)
    
    return U , S , V

In [29]:
A = np.array([[3,1,4,1],[5,9,2,6],[5,3,5,8],[9,7,9,3]])
U,S,V = plot_svd(A)

[[[ 2.51  2.37  2.22  1.97]
  [ 6.07  5.72  5.37  4.77]
  [ 5.63  5.31  4.99  4.43]
  [ 7.88  7.43  6.98  6.19]]

 [[ 0.64 -0.96  1.56 -1.42]
  [-1.19  1.8  -2.93  2.66]
  [-0.35  0.54 -0.87  0.79]
  [ 0.97 -1.47  2.38 -2.16]]

 [[-0.05 -0.45  0.14  0.44]
  [ 0.15  1.46 -0.46 -1.43]
  [-0.3  -2.84  0.89  2.78]
  [ 0.11  1.05 -0.33 -1.03]]

 [[-0.1   0.04  0.07  0.01]
  [-0.03  0.01  0.02  0.  ]
  [ 0.02 -0.01 -0.01 -0.  ]
  [ 0.04 -0.02 -0.03 -0.  ]]]

Combining all the above ones , we get our actual matrix A
[array([[3., 1., 4., 1.],
       [5., 9., 2., 6.],
       [5., 3., 5., 8.],
       [9., 7., 9., 3.]])]


In [33]:
print(U)

[[-0.21472623  0.37397651 -0.13150279 -0.89260362]
 [-0.5186023  -0.70137666  0.43020321 -0.23248147]
 [-0.48143993 -0.20822528 -0.83770916  0.15199076]
 [-0.67317152  0.56996016  0.30963782  0.35511962]]


In [9]:
print(S)

[21.23135684  6.43244475  4.88175527  0.14699287]


In [10]:
print(V)

[[-0.55120987 -0.51992284 -0.48804478 -0.43319766]
 [ 0.26483885 -0.40006067  0.65008996 -0.58923246]
 [ 0.07265877  0.69537763 -0.21865293 -0.68070665]
 [ 0.78787611 -0.29339674 -0.53980203 -0.04222983]]
